Updated header UI
HO-CTO/engineering-guidance-and-standards pull request #118
Opened 2023-06-06 11:11 UTC by keithkennedyHO

Using `organisationName` and `productName` in config to populate header and page titles fully.
Updated logo used in header to no longer contain text. 
Cleaned header styling.

2023-06-06 11:29 UTC, keithkennedyHO commented
Preview of updated header UI.

![image](https://github.com/HO-CTO/engineering-guidance-and-standards/assets/133027753/fb6512f4-d23d-44a3-9297-d4d648297956)

2023-06-08 10:45 UTC, jeff-horton-ho-sas requested changes

2023-06-08 10:45 UTC, jeff-horton-ho-sas commented on .eleventy.js
> +            productName: 'Engineering Guidance and Standards',
Title in head now shows as `Engineering Guidance and Standards - Engineering Guidance and Standards - Home Office` on home page. Consider hiding the product name in `index.md`.
```yaml
options:
  header:
    productName: ''
```

Otherwise LGTM

2023-06-08 11:32 UTC, jeff-horton-ho-sas approved these changes

2023-06-08 11:45 UTC, merged