Create 'immutable artefacts' pattern
HO-CTO/engineering-guidance-and-standards pull request #201
Opened 2023-07-26 09:09 UTC by edhamiltonHO

# Content change 

I can confirm:
- [ ] Content does not include any code or configuration changes (excluding frontmatter information)
- [ ] Content meets the content standards
e.g. [Writing a principle](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/writing-a-principle/) and [Writing a standard](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/writing-a-standard/)
- [ ] Content is suitable to open source, i.e.:
    - Content does not relate to unreleased gov policy
    - Content does not refer to anti-fraud mechanisms
    - Content does not include sensitive business logic

2023-07-26 09:48 UTC, aaronrussellHO commented on docs/patterns/immutable-artefacts.md
> +- Keep configuration out of the artefact. This should be provided using environment variables or similar external methods. See also Store Infrastructure and Configuration as Code.
Can this be a link to the standard for this?

2023-07-26 09:48 UTC, aaronrussellHO commented on docs/patterns/immutable-artefacts.md
> +An artefact is the deployable unit of code, for instance a Docker image, serverless package, or virtual machine image. You should build artefacts once, that you never modify, and use them across all
```suggestion
An artefact is the deployable unit of code, for instance a Docker image, serverless package, or virtual machine image. You should build artefacts once, afterwards and you should never modify them. If you need to make changes, a new artefact should be created. This helps with assurance and debugging incidents. 

An artefact should then be promoted between environments, this enables you to know what is running as the same arefact and code is used across different environments.
```
Think this reads a little clunky, how's this?

2023-07-26 09:48 UTC, aaronrussellHO commented on docs/patterns/immutable-artefacts.md
> +With proper versioning of your artefacts, you will be able to tie your environments back to a specific commit in your code-base, which is useful for investigation of incidents. Without immutable arte
```suggestion
With proper versioning of your artefacts, you will be able to tie your environments back to a specific commit in your code-base, which is useful for investigation of incidents. Without immutable artefacts you may have hidden state and/or subtle differences between environments, that make it very hard to understand the behaviour you are observing and undermine your confidence that something will continue to work when moved to another environment. You will also find it hard to recover from a future disaster, as you will need to rebuild your artefact first, and your build pipeline may be broken.
```

2023-07-26 09:48 UTC, aaronrussellHO commented on docs/patterns/immutable-artefacts.md
> +Immutable artefacts help us to know what we are running. They aid us in accurately reproducing environments and so help with:
```suggestion
Immutable artefacts help us to know what we are running. They aid us in accurately reproducing environments, this helps with:
```

2023-07-26 10:22 UTC, aaronrussellHO commented on docs/patterns/immutable-artefacts.md
> +- Deployment
Does it need a patterns tag?

2023-07-26 11:15 UTC, edhamiltonHO commented on docs/patterns/immutable-artefacts.md
> +- Deployment
Patterns tag is automatically applied during 11ty process, by virtue of being in the patterns subdirectory 🙂

2023-07-26 11:17 UTC, edhamiltonHO commented on docs/patterns/immutable-artefacts.md
> +- Keep configuration out of the artefact. This should be provided using environment variables or similar external methods. See also Store Infrastructure and Configuration as Code.
Yes, can update this as soon as the infrastructure as code standard is merged

2023-07-27 10:07 UTC, edhamiltonHO commented on docs/patterns/immutable-artefacts.md
> +An artefact is the deployable unit of code, for instance a Docker image, serverless package, or virtual machine image. You should build artefacts once, that you never modify, and use them across all
Have rewritten this entirely to be clearer on what an immutable artefact is

2023-07-27 10:11 UTC, aaronrussellHO approved these changes

2023-08-03 09:30 UTC, ezramorris requested changes

2023-08-03 09:30 UTC, ezramorris commented on docs/patterns/immutable-artefacts.md
> +```
```suggestion
- Store artefacts in a suitable artefact repository with a unique version identifier. Versioning should follow a common pattern, and be automated where possible, for example using [Semantic Versioning](https://semver.org/) or simply the build number.
```

I think the example is a bit confusing. Suggest referring to SemVer; it covers things like pre-release builds.

2023-08-03 09:53 UTC, ezramorris approved these changes

2023-08-03 12:00 UTC, edhamiltonHO commented on docs/patterns/immutable-artefacts.md
> +- Keep configuration out of the artefact. This should be provided using environment variables or similar external methods. See also Store Infrastructure and Configuration as Code.
Now that the infrastructure and configuration as code standard is focussed exclusively on infrastructure as code this link is not relevant any more

2023-08-03 12:02 UTC, merged