Create 'Design from evidence' principle
HO-CTO/engineering-guidance-and-standards pull request #218
Opened 2023-08-04 15:03 UTC by edhamiltonHO

Will close #113 

# Content change 
I can confirm:
- [ ] Content does not include any code or configuration changes (excluding frontmatter information)
- [ ] Content meets the content standards
e.g. [Writing a principle](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/writing-a-principle/) and [Writing a standard](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/writing-a-standard/)
- [ ] Content is suitable to open source, i.e.:
    - Content does not relate to unreleased gov policy
    - Content does not refer to anti-fraud mechanisms
    - Content does not include sensitive business logic

2023-08-04 15:12 UTC, aaronrussellHO approved these changes

2023-08-09 15:25 UTC, RobJohnson-HO requested changes
Some slight re-wording to help ease readability.

2023-08-09 15:25 UTC, RobJohnson-HO commented on docs/principles/design-from-evidence.md
> +Evidence-based decisions improve our ability to meet user needs. Without evidence of why we do things and their impact, it is hard to know what problems are, what features should be implemented and h
Missing "there".
```suggestion
Evidence-based decisions improve our ability to meet user needs. Without evidence of why we do things and their impact, it is hard to know what problems there are, what features should be implemented and how best to maintain our products.
```

2023-08-09 15:25 UTC, RobJohnson-HO commented on docs/principles/design-from-evidence.md
> +Successfully meeting user needs requires a proven understanding of user experience. Ensuring that the evidence we base our decisions on is up to date, valid and transparent allows us to iterate with
This sentence is a bit clunky.

```suggestion
Successfully meeting user needs requires a proven understanding of user experience.  We must ensure that the evidence we base our decisions on is up to date, valid and transparent.  This allows us to iterate with short feedback loops and provide value back to our users more quickly.   This applies across the whole lifecycle of a product. Evidence can be drawn from user research and other non-functional elements, for example legal, security, performance and other compliance requirements.
```

2023-08-09 15:25 UTC, RobJohnson-HO commented on docs/principles/design-from-evidence.md
> +Designing from evidence, and documenting that effectively, allows people to understand the intent behind design choices. This can help to reduce cost, where only valid requirements are met. This also
```suggestion
Designing from evidence, and documenting that effectively, allows people to understand the intent behind design choices. This can help to reduce cost by only meeting valid requirements. This also aids in the future maintainability of products because it is clearer why things were done, and the potential for regression of functionality is reduced. Designing test approaches based on good evidence of the correct requirements gives assurance and greater confidence in the product.
```

2023-08-09 15:25 UTC, RobJohnson-HO commented on docs/principles/design-from-evidence.md
> +- Provide evidence for design decisions in documentation and adhere to the [minimal documentation standard]({{ '/standards/minimal-documentation-set-for-a-product/' | url }}) - technical decision log
```suggestion
- Provide evidence for design decisions in documentation and adhere to the [minimal documentation standard]({{ '/standards/minimal-documentation-set-for-a-product/' | url }}) 
- Use technical decision logs and other useful design artefacts for assurance, maintainability and extensibility
```

2023-08-09 15:30 UTC, edhamiltonHO commented on docs/principles/design-from-evidence.md
> +- Provide evidence for design decisions in documentation and adhere to the [minimal documentation standard]({{ '/standards/minimal-documentation-set-for-a-product/' | url }}) - technical decision log
Going to leave this one as is. The point on technical decision logs is intended to be a specific example of providing evidence for design decisions in documentation

2023-08-09 15:38 UTC, RobJohnson-HO approved these changes
LGTM

2023-08-09 15:46 UTC, merged